import './styles/accent.css';
import './styles/styles.css';
import './styles/footer.css';
import './styles/cinema-chrome.css';
import './styles/offering.css';
import './lib/funnelInit';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { Accessibility } from './pages/Accessibility';
createRoot(document.getElementById('root')!).render(<StrictMode><Accessibility /></StrictMode>);
