import './styles/accent.css';
import './styles/styles.css';
import './styles/footer.css';
import './styles/cinema-chrome.css';
import './styles/offering.css';
import './styles/sections.css';
import './styles/geo-hamptons.css';
import './lib/funnelInit';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { Hamptons } from './pages/Hamptons';
createRoot(document.getElementById('root')!).render(<StrictMode><Hamptons /></StrictMode>);
