import './styles/accent.css';
import './styles/styles.css';
import './styles/footer.css';
import './styles/cinema-chrome.css';
import './styles/offering.css';
import './styles/sections.css';
import './styles/geo-new-jersey.css';
import './lib/funnelInit';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { NewJersey } from './pages/NewJersey';
createRoot(document.getElementById('root')!).render(<StrictMode><NewJersey /></StrictMode>);
