import type { Glass, Identity, Taste, Accord } from './profilerData';

export interface LibraryCocktail {
  id: string;
  name: string;
  archetype: string;
  tags: {
    identity: Identity[];
    taste: Taste[];
    accord: Accord[];
    facets?: string[];
  };
  tagline: string;
  ingredients: string[];
  instructions: string[];
  sensoryNarrative: string;
  colorProfile: string;
  tint: string;
  glass: Glass;
  sourceNote?: string;
}

// The owner's own 64 cocktails. Verbatim ingredients, measures and method.
// Names and prose (tagline, sensoryNarrative) are the house voice.
export const cocktailLibrary: LibraryCocktail[] = [
  {
    id: 'smoky-sirocco',
    name: 'Smoky Sirocco',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Rebel'], taste: ['Smoke'], accord: ['Bitter & Long'], facets: ['mezcal', 'smoky', 'citrus'] },
    tagline: 'Desert wind off the agave fields - smoke, tart pomegranate, a whisper of salt.',
    ingredients: [
      '1.5 oz Mezcal',
      '0.75 oz Pomegranate Molasses',
      '0.5 oz Lime Juice',
      '0.5 oz Agave Nectar',
      '1 dash Orange Bitters',
      'Sea salt (optional)',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain over fresh ice.',
      'Garnish with dehydrated lime and dried hibiscus.',
    ],
    sensoryNarrative: 'Woodsmoke meets tart pomegranate and bright lime, rounded by agave and a faint saline edge.',
    colorProfile: 'Smoky garnet over ice',
    tint: 'oklch(55% 0.12 25)',
    glass: 'rocks',
  },
  {
    id: 'maya-basil',
    name: 'Maya Basil',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Hunter'], taste: ['Smoke', 'Frost'], accord: ['Bitter & Long'], facets: ['mezcal', 'smoky', 'citrus'] },
    tagline: 'Garden-fresh basil and pineapple lifted by mezcal smoke and soda.',
    ingredients: [
      '1.5 oz Mezcal',
      '0.75 oz Basil Syrup',
      '0.75 oz Lemon Juice',
      '1 oz Pineapple Puree',
      '1 dash Angostura',
      'Soda to top',
    ],
    instructions: [
      'Shake all (except soda) with ice.',
      'Strain over ice.',
      'Top with soda.',
      'Garnish with dehydrated pineapple and basil.',
    ],
    sensoryNarrative: 'Sweet pineapple and herbal basil ride a current of mezcal smoke into a crisp, fizzy finish.',
    colorProfile: 'Hazy gold-green long drink',
    tint: 'oklch(78% 0.09 110)',
    glass: 'highball',
  },
  {
    id: 'verde',
    name: 'Verde',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Hunter'], taste: ['Smoke', 'Ember'], accord: ['Dry & Silent'], facets: ['mezcal', 'smoky', 'herbal'] },
    tagline: 'A green, herbal reckoning - cilantro, chartreuse and a chili-rimmed silk.',
    ingredients: [
      '1.5 oz Mezcal',
      '0.5 oz Lime Juice',
      '0.25 oz Agave Nectar',
      '0.5 oz Cilantro Syrup',
      '0.25 oz Green Chartreuse',
      '1 oz Aquafaba',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Double-strain into a coupe.',
      'Garnish with dehydrated lime over a chili rim.',
    ],
    sensoryNarrative: 'Smoke and alpine herbs over fresh cilantro and lime, with a silken foam and a chili tingle.',
    colorProfile: 'Pale herbal green with white crown',
    tint: 'oklch(82% 0.09 135)',
    glass: 'coupe',
  },
  {
    id: 'aztec-velvet',
    name: 'Aztec Velvet',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Hunter'], taste: ['Smoke', 'Ember'], accord: ['Sweet & Short'], facets: ['mezcal', 'creamy', 'smoky'] },
    tagline: 'Mezcal, cream and cacao banked over ancho heat.',
    ingredients: [
      '1.5 oz Mezcal',
      '1 oz Heavy Cream',
      '0.5 oz Creme de Cacao',
      '0.5 oz Coffee Liqueur',
      '0.25 oz Ancho Chile Syrup',
      'Sea salt (optional)',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain over a large cube.',
      'Garnish with dehydrated orange and chili threads.',
    ],
    sensoryNarrative: 'Velvety cream and chocolate wrap around smoky mezcal, with a slow ancho-chili warmth on the finish.',
    colorProfile: 'Mocha velvet over a clear cube',
    tint: 'oklch(50% 0.05 60)',
    glass: 'rocks',
  },
  {
    id: 'aegean-frappe',
    name: 'Aegean Frappe',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Hunter'], taste: ['Frost'], accord: ['Dry & Silent'], facets: ['absinthe', 'anise'] },
    tagline: 'Absinthe blitzed to snow - pure anise, ice-cold and austere.',
    ingredients: [
      '1.5 oz Absinthe',
      '10 ice cubes, crushed',
      'Sea salt (optional)',
    ],
    instructions: [
      'Blend to a fine snow.',
      'Garnish with star anise and dehydrated citrus.',
    ],
    sensoryNarrative: 'Cold, clean anise and licorice over crushed ice, dry and bracing from start to finish.',
    colorProfile: 'Pale green-white snow',
    tint: 'oklch(90% 0.04 140)',
    glass: 'highball',
  },
  {
    id: 'milos-mint-frappe',
    name: 'Milos Mint Frappe',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Rebel'], taste: ['Frost'], accord: ['Bitter & Long'], facets: ['absinthe', 'anise'] },
    tagline: 'Anise and fresh mint over crushed ice, lengthened with soda.',
    ingredients: [
      '1.5 oz Absinthe',
      '0.5 oz Simple Syrup',
      '5 mint leaves',
      'Soda to top',
    ],
    instructions: [
      'Shake absinthe, syrup and mint with ice.',
      'Pour over crushed ice.',
      'Top with soda.',
      'Garnish with dried mint.',
    ],
    sensoryNarrative: 'Cool mint and licorice anise lift on the soda, long and refreshing with a dry herbal close.',
    colorProfile: 'Frosted pale green',
    tint: 'oklch(88% 0.05 145)',
    glass: 'highball',
  },
  {
    id: 'milk-of-poseidon',
    name: 'Milk of Poseidon',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Mystic'], taste: ['Frost'], accord: ['Sweet & Short'], facets: ['absinthe', 'creamy', 'anise'] },
    tagline: 'Vanilla ice cream blended with absinthe - dessert with a licorice secret.',
    ingredients: [
      '2-3 scoops Vanilla Ice Cream',
      '1.5 oz Absinthe',
    ],
    instructions: [
      'Blend until smooth.',
      'Garnish with edible flowers and dried melon.',
    ],
    sensoryNarrative: 'Cold creamy vanilla folds into anise and herbs, sweet and soft with a lingering licorice hum.',
    colorProfile: 'Pale cream with a green tinge',
    tint: 'oklch(92% 0.03 130)',
    glass: 'coupe',
  },
  {
    id: 'death-on-the-balcony',
    name: 'Death on the Balcony',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Mystic'], taste: ['Frost'], accord: ['Dry & Silent'], facets: ['absinthe', 'sparkling', 'anise'] },
    tagline: 'Absinthe and mint laced through brut champagne.',
    ingredients: [
      '0.25 oz Lemon Juice',
      '0.25 oz Mint Simple Syrup',
      '1 oz Absinthe',
      '3 oz Brut Champagne',
    ],
    instructions: [
      'Build lemon, mint syrup and absinthe in the glass.',
      'Top with champagne.',
      'Garnish with dehydrated lemon and dried mint.',
    ],
    sensoryNarrative: 'Bone-dry bubbles carry anise and cool mint over a thread of lemon, crisp and elegant.',
    colorProfile: 'Pale gold with a green cast',
    tint: 'oklch(90% 0.04 120)',
    glass: 'coupe',
  },
  {
    id: 'ionian-mule',
    name: 'Ionian Mule',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Mystic'], taste: ['Ember', 'Frost'], accord: ['Spicy & Loud'], facets: ['absinthe', 'anise'] },
    tagline: 'A mule with a licorice heart - ginger heat over absinthe.',
    ingredients: [
      '0.5 oz Lime Juice',
      '1.5 oz Absinthe',
      'Ginger Beer to fill',
      'Bitters (optional)',
      'Sea salt (optional)',
    ],
    instructions: [
      'Build lime and absinthe over ice.',
      'Top with ginger beer.',
      'Garnish with dehydrated lime and dried thyme.',
    ],
    sensoryNarrative: 'Spicy ginger and lime crackle over cool anise, dry and loud with a herbal lift.',
    colorProfile: 'Cloudy pale gold',
    tint: 'oklch(85% 0.06 110)',
    glass: 'highball',
  },
  {
    id: 'delos-layers',
    name: 'Delos Layers',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Mystic'], taste: ['Bloom'], accord: ['Sweet & Short'], facets: ['absinthe', 'creamy', 'anise'] },
    tagline: 'A layered shot - melon, cream and absinthe in three strata.',
    ingredients: [
      '0.75 oz Midori',
      '0.75 oz Irish Cream',
      '0.75 oz Absinthe',
    ],
    instructions: [
      'Layer in order: Midori, then Irish Cream, then Absinthe.',
      'Garnish with dried flowers.',
    ],
    sensoryNarrative: 'Sweet melon and creamy chocolate give way to a sharp anise finish, layer by layer.',
    colorProfile: 'Green, cream and pale strata',
    tint: 'oklch(80% 0.1 140)',
    glass: 'coupe',
  },
  {
    id: 'cretes-hidden-gem',
    name: "Crete's Hidden Gem",
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Mystic'], taste: ['Bloom', 'Frost'], accord: ['Sweet & Short'], facets: ['absinthe', 'creamy', 'floral'] },
    tagline: 'Almond and cream around a hidden core of anise.',
    ingredients: [
      '1.5 oz Absinthe',
      '0.5 oz Almond Syrup',
      '1 oz Almond Milk',
      '1 oz Heavy Cream',
      '1 oz Aquafaba',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Strain.',
      'Garnish with dried lavender and dehydrated lime.',
    ],
    sensoryNarrative: 'Soft almond and cream cloak the anise, with a floral lavender lift over a silken body.',
    colorProfile: 'Pale almond cream',
    tint: 'oklch(91% 0.03 110)',
    glass: 'rocks',
  },
  {
    id: 'harrys-midnight-snack',
    name: "Harry's Midnight Snack",
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Lover'], taste: ['Bloom'], accord: ['Bitter & Long'], facets: ['amaro', 'creamy'] },
    tagline: 'Fernet and cream over orange - a bittersweet nightcap.',
    ingredients: [
      '0.5 orange wheel',
      '1 oz Heavy Cream',
      '5 drops saline',
      '1 oz White Creme de Cacao',
      '1.5 oz Fernet-Branca',
    ],
    instructions: [
      'Dry shake to emulsify.',
      'Add ice and shake again.',
      'Double-strain.',
      'Garnish with freeze-dried orange.',
    ],
    sensoryNarrative: 'Bitter menthol Fernet softened by cream and chocolate, with bright orange cutting the richness.',
    colorProfile: 'Dusty caramel cream',
    tint: 'oklch(70% 0.05 70)',
    glass: 'coupe',
  },
  {
    id: 'chocolate-punch',
    name: 'Chocolate Punch',
    archetype: 'The Lover',
    tags: { identity: ['Lover'], taste: ['Bloom'], accord: ['Sweet & Short'], facets: ['creamy', 'floral'] },
    tagline: 'Cognac, port and cacao whipped to a dessert froth.',
    ingredients: [
      '1 oz Pierre Ferrand Cognac',
      '0.5 oz Ruby Port',
      '0.5 oz Creme de Cacao',
      '0.25 oz Semi-Rich Simple Syrup',
      '1 oz Heavy Cream',
    ],
    instructions: [
      'Shake all to a froth.',
      'Strain.',
      'Dust with grated chocolate and add a dried cherry.',
    ],
    sensoryNarrative: 'Rich chocolate and dark berry from the port, smoothed by cognac and a creamy, dessert-sweet body.',
    colorProfile: 'Deep cocoa-rose froth',
    tint: 'oklch(55% 0.07 30)',
    glass: 'coupe',
  },
  {
    id: 'levantine-coffee',
    name: 'Levantine Coffee',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Hunter'], taste: ['Smoke', 'Ember'], accord: ['Sweet & Short'], facets: ['creamy', 'citrus'] },
    tagline: 'Cognac and Grand Marnier in hot coffee under whipped cream.',
    ingredients: [
      '1 oz Grand Marnier',
      '1 oz Cognac',
      '0.25 oz Simple Syrup',
      '3 oz hot strong coffee',
      'Lightly whipped cream',
    ],
    instructions: [
      'Build spirits, syrup and coffee in the glass.',
      'Float the lightly whipped cream.',
      'Garnish with chocolate shavings.',
    ],
    sensoryNarrative: 'Hot roasted coffee meets warm cognac and candied orange, finished with a cool cream cap.',
    colorProfile: 'Dark coffee under white cream',
    tint: 'oklch(45% 0.04 60)',
    glass: 'highball',
  },
  {
    id: 'mykonos-breeze',
    name: 'Mykonos Breeze',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Rebel'], taste: ['Bloom'], accord: ['Sweet & Short'], facets: ['floral', 'citrus'] },
    tagline: 'Apple brandy and scotch over a rosy grenadine silk.',
    ingredients: [
      "1 oz Laird's Apple Brandy",
      '0.5 oz Monkey Shoulder',
      '0.75 oz Lime Juice',
      '0.5 oz Grenadine',
      '1 oz Aquafaba',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Double-strain.',
      'Garnish with dehydrated apple and hibiscus.',
    ],
    sensoryNarrative: 'Orchard apple and a touch of malt over tart lime, with rosy grenadine and a silken foam.',
    colorProfile: 'Blush rose with white crown',
    tint: 'oklch(72% 0.1 20)',
    glass: 'coupe',
  },
  {
    id: 'aegean-rose',
    name: 'Aegean Rose',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Rebel'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['sparkling', 'floral'] },
    tagline: 'Strawberry and celery brightened with brut bubbles.',
    ingredients: [
      '2 oz Strawberry puree',
      '0.33 oz Celery juice',
      '0.33 oz Lemon juice',
      '0.33 oz Simple Syrup',
      'Brut sparkling to top',
    ],
    instructions: [
      'Stir the non-sparkling ingredients.',
      'Strain into a flute.',
      'Top with sparkling wine.',
      'Garnish with dehydrated strawberry.',
    ],
    sensoryNarrative: 'Ripe strawberry and a savory celery edge over dry, lively bubbles.',
    colorProfile: 'Pale strawberry pink',
    tint: 'oklch(80% 0.08 15)',
    glass: 'coupe',
  },
  {
    id: 'aviation',
    name: 'Aviation',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Mystic'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['gin', 'floral', 'citrus'] },
    tagline: 'Gin, maraschino and a single drop of violet.',
    ingredients: [
      '1.5 oz Plymouth Gin',
      '0.5 oz Lemon Juice',
      '0.5 oz Simple Syrup',
      '0.25 oz Maraschino',
      '1 drop Creme de Violette',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain.',
      'Garnish with a brandied cherry.',
    ],
    sensoryNarrative: 'Juniper and bright lemon meet cherry-floral maraschino and a faint violet perfume.',
    colorProfile: 'Pale silvery violet',
    tint: 'oklch(85% 0.04 300)',
    glass: 'nicknora',
  },
  {
    id: 'aeolis-crimson',
    name: 'Aeolis Crimson',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Lover'], taste: ['Bloom'], accord: ['Bitter & Long'], facets: ['gin', 'floral'] },
    tagline: 'Beet and pomegranate stain gin a deep crimson.',
    ingredients: [
      '1.5 oz Gin',
      '1.4 oz Beet puree',
      '1 oz Pomegranate Shrub',
      '0.7 oz Ruby Port',
      "1 dash Peychaud's",
      '0.7 oz Lime & Agave',
      'Salt (optional)',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain over ice.',
      'Garnish with a beet chip.',
    ],
    sensoryNarrative: 'Earthy beet and tart pomegranate over juniper, with a dark port depth and a tangy shrub bite.',
    colorProfile: 'Deep beet crimson',
    tint: 'oklch(48% 0.13 20)',
    glass: 'rocks',
  },
  {
    id: 'hydras-flame',
    name: "Hydra's Flame",
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Lover'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['gin', 'floral'] },
    tagline: 'Dragon fruit and prickly pear under an absinthe mist.',
    ingredients: [
      '1.5 oz Gin',
      '0.35 oz Dragon Fruit puree',
      '1.4 oz Prickly Pear puree',
      '0.7 oz Lime & Agave',
      'Absinthe mist (optional)',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain.',
      'Mist with absinthe.',
      'Garnish with dried dragon fruit and hibiscus.',
    ],
    sensoryNarrative: 'Bright tropical prickly pear and dragon fruit over juniper, with a faint anise mist on the nose.',
    colorProfile: 'Vivid magenta-pink',
    tint: 'oklch(65% 0.16 5)',
    glass: 'rocks',
  },
  {
    id: 'galatea-75',
    name: 'Galatea 75',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Lover'], taste: ['Frost'], accord: ['Dry & Silent'], facets: ['gin', 'sparkling', 'citrus'] },
    tagline: 'A French 75 in spirit - gin, lemon and brut bubbles.',
    ingredients: [
      '1.5 oz Gin',
      '0.75 oz Lemon Juice',
      '0.5 oz Simple Syrup',
      'Brut sparkling to fill',
    ],
    instructions: [
      'Shake gin, lemon and syrup with ice.',
      'Strain into a flute.',
      'Top with sparkling wine.',
      'Garnish with dehydrated lemon.',
    ],
    sensoryNarrative: 'Crisp lemon and juniper sharpened by dry, persistent bubbles.',
    colorProfile: 'Pale citrus gold',
    tint: 'oklch(90% 0.05 100)',
    glass: 'coupe',
  },
  {
    id: 'naxos-storm',
    name: 'Naxos Storm',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Rebel'], taste: ['Frost'], accord: ['Dry & Silent'], facets: ['gin', 'herbal', 'citrus'] },
    tagline: 'Gin under a brewing storm of chartreuse and absinthe.',
    ingredients: [
      '1.5 oz Gin',
      '0.25 oz Absinthe',
      '0.25 oz Green Chartreuse',
      '0.75 oz Lemon Juice',
      '0.75 oz Simple Syrup',
      '1 oz Aquafaba',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Strain.',
      'Float a little chartreuse and garnish with dried sage.',
    ],
    sensoryNarrative: 'Juniper and lemon under alpine chartreuse and anise, with a herbal, silky body.',
    colorProfile: 'Pale green-gold with foam',
    tint: 'oklch(85% 0.07 120)',
    glass: 'coupe',
  },
  {
    id: 'santorini-tide',
    name: 'Santorini Tide',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Rebel'], taste: ['Frost', 'Smoke'], accord: ['Dry & Silent'], facets: ['gin', 'smoky'] },
    tagline: 'Cucumber, seaweed and squid ink - the sea in a glass.',
    ingredients: [
      '1.5 oz Gin',
      '0.35 oz Roasted Seaweed syrup',
      '1.4 oz Cucumber puree',
      '0.7 oz Squid Ink',
      '0.7 oz Ginger Syrup',
      '0.7 oz Lime & Agave',
    ],
    instructions: [
      'Rim the glass with smoked salt.',
      'Shake all with ice.',
      'Strain.',
      'Garnish with dried seaweed.',
    ],
    sensoryNarrative: 'Cool cucumber and briny roasted seaweed over juniper, with ginger warmth and a smoky salt rim.',
    colorProfile: 'Inky slate grey-green',
    tint: 'oklch(40% 0.03 200)',
    glass: 'coupe',
  },
  {
    id: 'ithaca-blossom',
    name: 'Ithaca Blossom',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Mystic'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['floral', 'citrus'] },
    tagline: 'Pisco with dandelion and lemon verbena in bloom.',
    ingredients: [
      '1.5 oz Pisco',
      '0.35 oz Dandelion syrup',
      '1.4 oz Lemon Juice',
      '1 oz Aquafaba',
      '0.18 oz Lemon Verbena',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Strain.',
      'Garnish with dried flowers and verbena.',
    ],
    sensoryNarrative: 'Grapey pisco and bright lemon over delicate dandelion and verbena, floral and clean.',
    colorProfile: 'Pale floral gold',
    tint: 'oklch(89% 0.05 100)',
    glass: 'coupe',
  },
  {
    id: 'daily-rituals',
    name: 'Daily Rituals',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Mystic'], taste: ['Smoke'], accord: ['Sweet & Short'], facets: ['rum', 'creamy', 'amaro'] },
    tagline: 'Cold brew, aged rum and amaro whipped to a coffee silk.',
    ingredients: [
      '2 dashes Chocolate Bitters',
      '0.75 oz Cold Brew Concentrate',
      '0.75 oz Meletti',
      '0.75 oz Aged Rum',
      '0.5 oz Coffee Liqueur',
      '0.25 oz Licor 43',
      '1 oz Aquafaba',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Double-strain.',
      'Dust with cocoa.',
    ],
    sensoryNarrative: 'Roasted coffee and cocoa over warm aged rum and bittersweet amaro, with a vanilla-silk finish.',
    colorProfile: 'Deep coffee brown with crema',
    tint: 'oklch(48% 0.04 55)',
    glass: 'coupe',
  },
  {
    id: 'levante-funk',
    name: 'Levante Funk',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Mystic'], taste: ['Ember'], accord: ['Spicy & Loud'], facets: ['rum', 'anise'] },
    tagline: 'Funky rum, ginger and absinthe in a loud, dark dance.',
    ingredients: [
      '0.5 oz Lime Juice',
      "1.5 oz Gosling's Rum",
      '0.5 oz Lemon Juice',
      '0.5 oz Absinthe',
      '0.25 oz Simple Syrup',
      'Ginger Beer to fill',
      'Grenadine to taste',
    ],
    instructions: [
      'Shake all (except ginger beer and grenadine) with ice.',
      'Strain over ice.',
      'Top with ginger beer and add grenadine to taste.',
      'Garnish with dehydrated lime.',
    ],
    sensoryNarrative: 'Dark molasses rum and ginger heat with anise and citrus, loud and rolling with a rosy sweet edge.',
    colorProfile: 'Dark amber with a red drift',
    tint: 'oklch(55% 0.1 45)',
    glass: 'highball',
  },
  {
    id: 'carthage-spice',
    name: 'Carthage Spice',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Hunter'], taste: ['Ember'], accord: ['Spicy & Loud'], facets: ['rum', 'citrus'] },
    tagline: 'Spiced rum and ginger sharpened with lemon.',
    ingredients: [
      '1.5 oz Spiced Rum',
      '0.7 oz Ginger Syrup',
      '1 oz Lemon Juice',
      'Sea salt (optional)',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain into a martini glass.',
      'Garnish with dehydrated lemon and a cinnamon stick.',
    ],
    sensoryNarrative: 'Warm baking spice from the rum meets ginger heat and a tart lemon snap.',
    colorProfile: 'Warm spiced amber',
    tint: 'oklch(70% 0.09 70)',
    glass: 'nicknora',
  },
  {
    id: 'myrto-garden',
    name: 'Myrto Garden',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Rebel'], taste: ['Frost', 'Bloom'], accord: ['Sweet & Short'], facets: ['vodka', 'floral'] },
    tagline: 'Mint and blackcurrant over a clean vodka base.',
    ingredients: [
      '0.5 oz Lime juice',
      '5 mint leaves',
      '0.5 oz Simple Syrup',
      '1.5 oz Vodka',
      '1 dash Cassis',
      'Soda (optional)',
    ],
    instructions: [
      'Muddle the mint.',
      'Shake with the other ingredients and ice.',
      'Strain over ice.',
      'Float the cassis and garnish with dried blackcurrants.',
    ],
    sensoryNarrative: 'Cool mint and lime over clean vodka, with a dark blackcurrant sweetness drifting through.',
    colorProfile: 'Pale with a purple drift',
    tint: 'oklch(70% 0.1 320)',
    glass: 'highball',
  },
  {
    id: 'delphi-cocoa',
    name: 'Delphi Cocoa',
    archetype: 'The Lover',
    tags: { identity: ['Lover'], taste: ['Bloom'], accord: ['Sweet & Short'], facets: ['vodka', 'creamy'] },
    tagline: 'Vodka, hazelnut and chocolate in a sleek martini.',
    ingredients: [
      '1.5 oz Vodka',
      '0.5 oz Frangelico',
      '1 oz Chocolate Liqueur',
      'Sea salt (optional)',
    ],
    instructions: [
      'Shake all with ice.',
      'Double-strain.',
      'Garnish with chocolate shavings and a dried rose petal.',
    ],
    sensoryNarrative: 'Smooth chocolate and toasted hazelnut over clean vodka, dessert-sweet and round.',
    colorProfile: 'Glossy chocolate brown',
    tint: 'oklch(45% 0.05 50)',
    glass: 'nicknora',
  },
  {
    id: 'beirut-espresso',
    name: 'Beirut Espresso',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Lover'], taste: ['Smoke'], accord: ['Sweet & Short'], facets: ['vodka', 'spirit-forward'] },
    tagline: 'A wide-awake espresso martini with a coffee crema.',
    ingredients: [
      '1.5 oz Vodka',
      '0.5 oz Kahlua',
      '1 oz fresh Espresso, cooled',
      '0.25 oz Simple Syrup',
    ],
    instructions: [
      'Shake hard with ice.',
      'Strain.',
      'Garnish with 3 coffee beans and cinnamon.',
    ],
    sensoryNarrative: 'Bold roasted espresso over clean vodka and coffee liqueur, with a sweet crema and a cinnamon nose.',
    colorProfile: 'Dark espresso with crema',
    tint: 'oklch(42% 0.04 55)',
    glass: 'nicknora',
  },
  {
    id: 'nablus-pear',
    name: 'Nablus Pear',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Mystic'], taste: ['Bloom'], accord: ['Sweet & Short'], facets: ['vodka', 'floral'] },
    tagline: 'Pear vodka and elderflower stirred into pear puree.',
    ingredients: [
      '1.5 oz Pear Vodka',
      '0.7 oz Elderflower Liqueur',
      '~5 oz Pear Puree',
      'Salt (optional)',
    ],
    instructions: [
      'Build over ice.',
      'Stir to combine.',
      'Garnish with dehydrated pear and dried rosemary.',
    ],
    sensoryNarrative: 'Ripe pear and floral elderflower over a clean, faintly herbal base, soft and round.',
    colorProfile: 'Pale pear gold',
    tint: 'oklch(88% 0.06 95)',
    glass: 'rocks',
  },
  {
    id: 'rhodes-quencher',
    name: 'Rhodes Quencher',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Lover'], taste: ['Frost'], accord: ['Dry & Silent'], facets: ['vodka', 'herbal'] },
    tagline: 'Cucumber and mint over a botanical vodka base.',
    ingredients: [
      '1.5 oz Quinoa Vodka',
      '0.35 oz Horny Goat Weed Tea',
      '1.4 oz Cucumber puree',
      '0.7 oz Mint',
      '0.7 oz Lime & Agave',
      '1 drop Vanilla',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain over ice.',
      'Garnish with a dried cucumber chip.',
    ],
    sensoryNarrative: 'Crisp cucumber and cool mint over clean vodka, with a herbal-tea note and a whisper of vanilla.',
    colorProfile: 'Pale cucumber green',
    tint: 'oklch(86% 0.06 140)',
    glass: 'rocks',
  },
  {
    id: 'tel-aviv-garden',
    name: 'Tel Aviv Garden',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Rebel'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['vodka', 'sparkling', 'floral'] },
    tagline: 'Strawberry and rosemary lifted with dry bubbles.',
    ingredients: [
      '1.5 oz Vodka',
      '0.35 oz Rosemary syrup',
      '1.4 oz Strawberry Puree',
      '0.7 oz Lime & Agave',
      'Dry sparkling to top',
    ],
    instructions: [
      'Shake all (except sparkling) with ice.',
      'Strain into a flute.',
      'Top with sparkling wine.',
      'Garnish with dried rosemary and dehydrated strawberry.',
    ],
    sensoryNarrative: 'Ripe strawberry and piney rosemary over clean vodka and dry, lively bubbles.',
    colorProfile: 'Soft strawberry blush',
    tint: 'oklch(78% 0.09 18)',
    glass: 'coupe',
  },
  {
    id: 'rhodes-sunset',
    name: 'Rhodes Sunset',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Lover'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['vodka', 'floral', 'anise'] },
    tagline: 'Chokeberry vodka with rosemary and a kiss of absinthe.',
    ingredients: [
      '1.25 oz Chokeberry-infused Vodka',
      '0.25 oz Absinthe',
      '0.25 oz Simple Syrup',
      '0.5 oz Lemon Juice',
      '0.75 oz Rosemary Syrup',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain into a coupe.',
      'Garnish with dehydrated orange and dried rosemary.',
    ],
    sensoryNarrative: 'Dark chokeberry and piney rosemary over clean vodka, with a faint anise lift and a tart lemon edge.',
    colorProfile: 'Dusky berry purple',
    tint: 'oklch(55% 0.1 340)',
    glass: 'coupe',
  },
  {
    id: 'delos-passion',
    name: 'Delos Passion',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Lover'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['bourbon', 'sparkling', 'floral'] },
    tagline: 'Bourbon and lemon laced through dry bubbles.',
    ingredients: [
      '1 oz Bourbon',
      "2 drops Peychaud's",
      '0.5 oz Lemon Juice',
      '0.5 oz Simple Syrup',
      '1 drop Ricard',
      'Dry sparkling to fill',
    ],
    instructions: [
      'Stir the non-sparkling ingredients.',
      'Strain into a flute.',
      'Top with sparkling wine.',
      'Garnish with dried lemon and rose petals.',
    ],
    sensoryNarrative: 'Warm bourbon and bright lemon over dry bubbles, with a floral, faintly anise lift.',
    colorProfile: 'Pale rosy gold',
    tint: 'oklch(85% 0.05 60)',
    glass: 'coupe',
  },
  {
    id: 'aegean-harvest',
    name: 'Aegean Harvest',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Lover'], taste: ['Ember'], accord: ['Sweet & Short'], facets: ['bourbon', 'spirit-forward'] },
    tagline: 'Bourbon and apple cider banked with maple and cinnamon.',
    ingredients: [
      '1.5 oz Bourbon',
      '5 oz apple cider',
      '0.7 oz Maple Syrup',
      'Salt (optional)',
    ],
    instructions: [
      'Stir all with ice.',
      'Strain over ice.',
      'Garnish with dried apple and a cinnamon stick.',
    ],
    sensoryNarrative: 'Orchard apple cider and warm maple over oaky bourbon, with a cinnamon-spice finish.',
    colorProfile: 'Warm cider amber',
    tint: 'oklch(68% 0.09 65)',
    glass: 'rocks',
  },
  {
    id: 'cyclades-kiss',
    name: 'Cyclades Kiss',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Lover'], taste: ['Ember', 'Bloom'], accord: ['Spicy & Loud'], facets: ['bourbon', 'citrus'] },
    tagline: 'Bourbon and melon with a ginger kick.',
    ingredients: [
      '1.5 oz Bourbon',
      '0.5 oz Lemon Juice',
      '0.25 oz Simple Syrup',
      'Fresh ginger or 0.25 oz ginger syrup',
      '1 oz Melon Puree',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain over ice.',
      'Garnish with dehydrated melon and dried ginger.',
    ],
    sensoryNarrative: 'Sweet melon and bright lemon over oaky bourbon, with a warm ginger snap.',
    colorProfile: 'Pale melon gold',
    tint: 'oklch(82% 0.08 110)',
    glass: 'rocks',
  },
  {
    id: 'rhodes-dawn-sour',
    name: 'Rhodes Dawn Sour',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Mystic'], taste: ['Smoke'], accord: ['Dry & Silent'], facets: ['smoky', 'citrus'] },
    tagline: 'A scotch sour with an absinthe shadow and a silken foam.',
    ingredients: [
      '1.75 oz Scotch',
      '1 oz Lemon Juice',
      '0.75 oz Simple Syrup',
      '0.25 oz Absinthe',
      '1 oz Aquafaba',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Strain into a coupe.',
      'Garnish with dehydrated lemon.',
    ],
    sensoryNarrative: 'Malty scotch and bright lemon over a silky foam, with a faint smoke and anise undertow.',
    colorProfile: 'Pale gold with white crown',
    tint: 'oklch(85% 0.05 90)',
    glass: 'coupe',
  },
  {
    id: 'rusty-nail',
    name: 'Rusty Nail',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter'], taste: ['Ember'], accord: ['Dry & Silent'], facets: ['spirit-forward'] },
    tagline: 'Just scotch and Drambuie, stirred cold and slow.',
    ingredients: [
      '2 oz Monkey Shoulder',
      '1 oz Drambuie',
    ],
    instructions: [
      'Stir over ice.',
      'Strain over a large cube.',
      'Garnish with a dehydrated lemon peel or leave bare.',
    ],
    sensoryNarrative: 'Honeyed Drambuie and warm baking spice over malty scotch, spirit-forward and round.',
    colorProfile: 'Burnished amber',
    tint: 'oklch(64% 0.09 70)',
    glass: 'rocks',
  },
  {
    id: 'myrtos-sipper',
    name: 'Myrtos Sipper',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Lover'], taste: ['Ember'], accord: ['Dry & Silent'], facets: ['bourbon', 'spirit-forward'] },
    tagline: 'A bourbon Old Fashioned scented with vanilla and saffron.',
    ingredients: [
      '1.5 oz Bourbon',
      '0.35 oz Vanilla & Saffron syrup',
      '1 dash Angostura',
      '0.7 oz Orange zest/juice',
      '0.7 oz Agave Nectar',
    ],
    instructions: [
      'Stir all with ice.',
      'Strain over ice.',
      'Garnish with dehydrated orange.',
    ],
    sensoryNarrative: 'Oaky bourbon over warm vanilla and saffron, with bright orange and a soft agave sweetness.',
    colorProfile: 'Golden saffron amber',
    tint: 'oklch(70% 0.1 75)',
    glass: 'rocks',
  },
  {
    id: 'sazerac',
    name: 'Sazerac',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Mystic'], taste: ['Ember'], accord: ['Dry & Silent'], facets: ['spirit-forward', 'anise'] },
    tagline: 'Rye and cognac, stirred neat in an absinthe-rinsed glass.',
    ingredients: [
      'Dashes Angostura',
      "Dashes Peychaud's",
      '1 tsp Simple Syrup',
      '1 oz Rye',
      '1 oz Cognac',
      'Absinthe rinse',
    ],
    instructions: [
      'Rinse the glass with absinthe and discard the excess.',
      'Stir the remaining ingredients with ice.',
      'Strain neat into the rinsed glass.',
      'Garnish with a dehydrated lemon twist.',
    ],
    sensoryNarrative: 'Spicy rye and warm cognac wrapped in anise and bitters, dry, austere and aromatic.',
    colorProfile: 'Deep golden amber, neat',
    tint: 'oklch(62% 0.09 68)',
    glass: 'rocks',
  },
  {
    id: 'aeolian-poet',
    name: 'Aeolian Poet',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Mystic'], taste: ['Smoke', 'Ember'], accord: ['Dry & Silent'], facets: ['bourbon', 'spirit-forward'] },
    tagline: 'Bourbon, black walnut and espresso in a brooding old fashioned.',
    ingredients: [
      '1.5 oz Bourbon',
      '0.35 oz Chilled Espresso',
      '1.4 oz Black Walnut Husk syrup',
      '0.7 oz Allspice liqueur',
      '0.7 oz Rye (optional)',
      '0.7 oz Agave',
      'Salt (optional)',
    ],
    instructions: [
      'Stir all with ice.',
      'Strain over ice.',
      'Garnish with a smoking clove and dried bay.',
    ],
    sensoryNarrative: 'Oaky bourbon and dark espresso over bitter black walnut, with allspice warmth and a smoky clove nose.',
    colorProfile: 'Deep walnut brown',
    tint: 'oklch(45% 0.05 55)',
    glass: 'rocks',
  },
  {
    id: 'el-marrakesh',
    name: 'El Marrakesh',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Hunter'], taste: ['Bloom'], accord: ['Sweet & Short'], facets: ['tequila', 'floral'] },
    tagline: 'Tequila, date syrup and pomegranate with a rose finish.',
    ingredients: [
      '1.5 oz Tequila',
      '0.75 oz Date Syrup',
      '0.5 oz Lime Juice',
      '0.5 oz Pomegranate Puree',
      '1 dash Aromatic Bitters',
      'Salt (optional)',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain over ice.',
      'Garnish with dehydrated lime and dried rose petals.',
    ],
    sensoryNarrative: 'Earthy agave over rich date and tart pomegranate, with a floral rose lift and a tangy close.',
    colorProfile: 'Deep pomegranate red',
    tint: 'oklch(55% 0.13 22)',
    glass: 'rocks',
  },
  {
    id: 'thyme-paloma',
    name: 'Thyme Paloma',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Hunter'], taste: ['Frost'], accord: ['Bitter & Long'], facets: ['tequila', 'citrus', 'herbal'] },
    tagline: 'A herbal paloma - tequila, grapefruit and thyme over soda.',
    ingredients: [
      '1.5 oz Tequila Blanco',
      '0.75 oz Thyme-Infused Simple Syrup',
      '1 oz Grapefruit Juice',
      '0.5 oz Lime Juice',
      'Soda to top',
      'Salt or grapefruit bitters (optional)',
    ],
    instructions: [
      'Shake all (except soda) with ice.',
      'Strain over ice.',
      'Top with soda.',
      'Garnish with dried grapefruit and thyme.',
    ],
    sensoryNarrative: 'Bittersweet grapefruit and bright lime over crisp agave, with a savory thyme thread and a long fizz.',
    colorProfile: 'Pale grapefruit pink',
    tint: 'oklch(82% 0.07 30)',
    glass: 'highball',
  },
  {
    id: 'costa-fiesta',
    name: 'Costa Fiesta',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Rebel'], taste: ['Bloom', 'Ember'], accord: ['Sweet & Short'], facets: ['tequila', 'citrus'] },
    tagline: 'Mango and agave over tequila with a chili-salt rim.',
    ingredients: [
      '1.5 oz Tequila Blanco',
      '1 oz Mango Puree',
      '0.5 oz Agave Nectar',
      '0.5 oz Lime Juice',
      '1 oz Aquafaba',
      'Orange Bitters (optional)',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Double-strain.',
      'Garnish with dehydrated mango over a chili salt rim.',
    ],
    sensoryNarrative: 'Ripe mango and agave over crisp tequila and lime, with a silky foam and a chili-salt edge.',
    colorProfile: 'Sunny mango gold',
    tint: 'oklch(83% 0.11 80)',
    glass: 'coupe',
  },
  {
    id: 'ionian-spice',
    name: 'Ionian Spice',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Rebel'], taste: ['Ember'], accord: ['Spicy & Loud'], facets: ['anise', 'citrus'] },
    tagline: 'Ouzo and honey with a ginger bite.',
    ingredients: [
      '1.5 oz Ouzo',
      '0.75 oz Honey Syrup',
      '1 oz Lemon Juice',
      '0.5 oz Ginger Puree/Syrup',
      'Salt (optional)',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain over ice.',
      'Garnish with dehydrated lemon and candied ginger.',
    ],
    sensoryNarrative: 'Anise-forward ouzo and warm honey over bright lemon, with a loud ginger kick.',
    colorProfile: 'Cloudy honey gold',
    tint: 'oklch(82% 0.07 95)',
    glass: 'rocks',
  },
  {
    id: 'midnight-arak',
    name: 'Midnight Arak',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Lover'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['anise', 'floral'] },
    tagline: 'Arak, pomegranate and rosewater under a silken cap.',
    ingredients: [
      '1.5 oz Arak',
      '0.75 oz Pomegranate Molasses',
      '0.5 oz Lime Juice',
      '0.25 oz Rosewater',
      '1 oz Aquafaba (optional)',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Double-strain.',
      'Garnish with dried rose petals and dehydrated lime.',
    ],
    sensoryNarrative: 'Anise arak over tart pomegranate and delicate rosewater, floral and dry with a silken foam.',
    colorProfile: 'Pale rosy blush',
    tint: 'oklch(78% 0.07 12)',
    glass: 'coupe',
  },
  {
    id: 'petes-word',
    name: "Pete's Word",
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Mystic'], taste: ['Smoke'], accord: ['Bitter & Long'], facets: ['smoky', 'herbal', 'citrus'] },
    tagline: 'A Last Word gone smoky - equal parts, opposite forces.',
    ingredients: [
      '0.75 oz Smoky Scotch',
      '0.75 oz Green Chartreuse',
      '0.75 oz Maraschino Liqueur',
      '0.75 oz Lime Juice',
    ],
    instructions: [
      'Shake all with ice.',
      'Double-strain into a coupe.',
      'No garnish (optional lime).',
    ],
    sensoryNarrative: 'Peat smoke and alpine chartreuse over cherry maraschino and bright lime, a long bittersweet pull.',
    colorProfile: 'Pale herbal green-gold',
    tint: 'oklch(82% 0.08 125)',
    glass: 'coupe',
  },
  {
    id: 'gomme-campari-negroni',
    name: 'Gomme Campari Negroni',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Hunter'], taste: ['Ember'], accord: ['Bitter & Long'], facets: ['gin', 'amaro'] },
    tagline: 'The Negroni, equal parts, with a rounded gomme Campari.',
    ingredients: [
      '1 oz Dry Gin',
      '1 oz Sweet Vermouth',
      '1 oz Gomme Campari',
    ],
    instructions: [
      'Stir with ice.',
      'Strain over a large cube.',
      'Garnish with an orange twist.',
    ],
    sensoryNarrative: 'Bitter orange Campari and rich vermouth over juniper, bittersweet and long with a rounded body.',
    colorProfile: 'Deep ruby red',
    tint: 'oklch(55% 0.14 25)',
    glass: 'rocks',
  },
  {
    id: 'tunnel-negroni',
    name: 'Tunnel Negroni',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Hunter'], taste: ['Ember'], accord: ['Bitter & Long'], facets: ['gin', 'amaro'] },
    tagline: 'A drier Negroni - two vermouths, less Campari.',
    ingredients: [
      '1 oz Dry Gin',
      '1 oz Dry Vermouth',
      '2/3 oz Campari',
      '1/3 oz Sweet Vermouth',
    ],
    instructions: [
      'Stir with ice.',
      'Strain over a large cube.',
      'Garnish with an orange twist.',
    ],
    sensoryNarrative: 'Crisp dry vermouth and juniper over bitter Campari, drier and leaner with a long bitter finish.',
    colorProfile: 'Bright orange-red',
    tint: 'oklch(62% 0.13 35)',
    glass: 'rocks',
  },
  {
    id: 'eeyores-requiem',
    name: "Eeyore's Requiem",
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Hunter'], taste: ['Ember'], accord: ['Bitter & Long'], facets: ['amaro', 'gin'] },
    tagline: 'Campari leads a chorus of amari - profoundly bitter.',
    ingredients: [
      '1.5 oz Campari',
      '1 oz Bianco Vermouth',
      '0.5 oz Dry Gin',
      '0.25 oz Cynar',
      '0.25 oz Fernet Branca',
      '1 dash Angostura',
      '1 dash Orange Bitters',
    ],
    instructions: [
      'Stir with ice.',
      'Strain into a coupe.',
      'Garnish with a lemon twist.',
    ],
    sensoryNarrative: 'A deep stack of bitter Campari, Cynar and Fernet over crisp vermouth, austere and lingering.',
    colorProfile: 'Dark bitter red',
    tint: 'oklch(50% 0.13 28)',
    glass: 'coupe',
  },
  {
    id: 'montenegroni',
    name: 'Montenegroni',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Lover'], taste: ['Ember'], accord: ['Bitter & Long'], facets: ['amaro', 'gin'] },
    tagline: 'A softer Negroni built on Amaro Montenegro.',
    ingredients: [
      '1 1/3 oz Amaro Montenegro',
      '3/4 oz Dry Gin',
      '2/3 oz Sweet Vermouth',
    ],
    instructions: [
      'Stir with ice.',
      'Strain over a large cube.',
      'Garnish with an orange twist.',
    ],
    sensoryNarrative: 'Gentle orange-spice amaro over juniper and vermouth, bittersweet and rounded with an easy finish.',
    colorProfile: 'Warm amber-red',
    tint: 'oklch(58% 0.1 45)',
    glass: 'rocks',
  },
  {
    id: 'mezcal-bianco-negroni',
    name: 'Mezcal Bianco Negroni',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Mystic'], taste: ['Smoke'], accord: ['Bitter & Long'], facets: ['mezcal', 'smoky', 'amaro'] },
    tagline: 'A smoky white Negroni - mezcal, Suze and dry vermouth.',
    ingredients: [
      '1.5 oz Joven Mezcal',
      '0.75 oz Dry Vermouth',
      '0.75 oz Bitter Bianco (Suze)',
      '2 dashes Orange Bitters',
    ],
    instructions: [
      'Stir with ice.',
      'Strain over ice.',
      'Garnish with a grapefruit twist.',
    ],
    sensoryNarrative: 'Smoky mezcal over gentian-bitter Suze and crisp vermouth, dry and bracing with a citrus oil lift.',
    colorProfile: 'Pale straw with a smoky cast',
    tint: 'oklch(86% 0.05 100)',
    glass: 'rocks',
  },
  {
    id: 'winters-veil',
    name: "Winter's Veil",
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Mystic'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['gin', 'floral', 'herbal'] },
    tagline: 'Blackberry and rosemary under a chartreuse hush.',
    ingredients: [
      '1.5 oz Dry Gin',
      '0.75 oz Blackberry Puree',
      '0.25 oz Green Chartreuse',
      '1 oz Lime Juice',
      '1 rosemary sprig',
    ],
    instructions: [
      'Shake all with ice.',
      'Double-strain into a coupe.',
      'Garnish with a rosemary sprig.',
    ],
    sensoryNarrative: 'Dark blackberry and piney rosemary over juniper, with an alpine chartreuse lift and a tart lime edge.',
    colorProfile: 'Deep blackberry purple',
    tint: 'oklch(48% 0.1 330)',
    glass: 'coupe',
  },
  {
    id: 'frosty-serenade',
    name: 'Frosty Serenade',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Mystic'], taste: ['Smoke', 'Ember'], accord: ['Bitter & Long'], facets: ['smoky', 'amaro', 'spirit-forward'] },
    tagline: 'Smoky scotch and Drambuie woven with Fernet and spice.',
    ingredients: [
      '1.5 oz Talisker Ten',
      '0.75 oz Drambuie',
      '0.75 oz Sweet Vermouth',
      '0.5 oz Fernet Branca',
      '2 dashes Angostura',
      '1 dash Cinnamon Tincture',
    ],
    instructions: [
      'Stir with ice.',
      'Strain over a large cube.',
      'Garnish with a cinnamon stick and an orange twist.',
    ],
    sensoryNarrative: 'Peat smoke and honeyed Drambuie over bitter Fernet and vermouth, with a warm cinnamon-spice finish.',
    colorProfile: 'Dark spiced amber',
    tint: 'oklch(52% 0.07 55)',
    glass: 'rocks',
  },
  {
    id: 'the-last-word-perfected',
    name: 'The Last Word (Perfected)',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Mystic'], taste: ['Frost'], accord: ['Bitter & Long'], facets: ['gin', 'herbal', 'citrus'] },
    tagline: 'Equal parts, opposite forces - the green classic, perfected.',
    ingredients: [
      '1 oz Gin',
      '1 oz Green Chartreuse',
      '1 oz Maraschino',
      '1 oz Lime Juice',
      '2 dashes Cherry Bitters',
    ],
    instructions: [
      'Shake all with ice.',
      'Double-strain into a coupe.',
      'Garnish with a brandied cherry.',
    ],
    sensoryNarrative: 'Alpine herbs and bright lime over juniper and cherry maraschino, bracing with a long bitter cool.',
    colorProfile: 'Pale chartreuse green',
    tint: 'oklch(82% 0.1 140)',
    glass: 'coupe',
  },
  {
    id: 'elderflower-old-fashioned-enhanced',
    name: 'Elderflower Old Fashioned (Enhanced)',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Lover'], taste: ['Bloom', 'Ember'], accord: ['Dry & Silent'], facets: ['bourbon', 'floral', 'spirit-forward'] },
    tagline: 'A bourbon Old Fashioned brightened with an Etna liqueur.',
    ingredients: [
      '2 oz Bourbon',
      "0.5 oz Liquori dell'Etna",
      '2 dashes Angostura',
      '1 dash Orange bitters',
    ],
    instructions: [
      'Stir with ice.',
      'Strain over a large cube.',
      'Garnish with an orange twist.',
    ],
    sensoryNarrative: 'Oaky bourbon over warm botanical-citrus liqueur and aromatic bitters, dry and spirit-forward.',
    colorProfile: 'Deep amber',
    tint: 'oklch(62% 0.09 65)',
    glass: 'rocks',
  },
  {
    id: 'golden-pear-martini',
    name: 'Golden Pear Martini',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Hunter'], taste: ['Bloom'], accord: ['Dry & Silent'], facets: ['vodka', 'floral', 'spirit-forward'] },
    tagline: 'A pear martini - clean vodka, ripe pear, a dry vermouth thread.',
    ingredients: [
      '2 oz Vodka',
      '1 oz Liquore di Pera Coscia',
      '0.25 oz Dry vermouth',
    ],
    instructions: [
      'Stir with ice.',
      'Strain into a martini glass.',
      'Express a lemon peel over the surface.',
      'Garnish with a lemon peel.',
    ],
    sensoryNarrative: 'Ripe pear over clean vodka with a dry vermouth whisper and a bright lemon oil lift.',
    colorProfile: 'Pale golden pear',
    tint: 'oklch(88% 0.06 95)',
    glass: 'nicknora',
  },
  {
    id: 'olive-leaf-martini-improved',
    name: 'Olive Leaf Martini (Improved)',
    archetype: 'The Hunter',
    tags: { identity: ['Hunter', 'Mystic'], taste: ['Frost'], accord: ['Dry & Silent'], facets: ['gin', 'herbal', 'spirit-forward'] },
    tagline: 'A savory martini - gin, olive leaf and a touch of Tentura.',
    ingredients: [
      '2 oz Gin',
      '0.5 oz Olive Leaf Liqueur',
      '0.25 oz Tentura',
    ],
    instructions: [
      'Stir with ice.',
      'Strain into a martini glass.',
      'Garnish with an olive and rosemary.',
    ],
    sensoryNarrative: 'Crisp juniper and green olive-leaf over a faint warm-spice Tentura note, dry and savory.',
    colorProfile: 'Pale silvery green',
    tint: 'oklch(88% 0.04 130)',
    glass: 'nicknora',
  },
  {
    id: 'persimmon-saffron-sour',
    name: 'Persimmon & Saffron Sour',
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Hunter'], taste: ['Bloom', 'Ember'], accord: ['Sweet & Short'], facets: ['floral', 'citrus'] },
    tagline: 'A whiskey sour scented with persimmon and saffron.',
    ingredients: [
      '2 oz Whiskey',
      '0.5 oz Persimmon Liqueur',
      '0.25 oz Saffron Spiced Liqueur',
      '0.75 oz Lemon Juice',
      '0.5 oz Simple Syrup',
      'Egg white (optional)',
    ],
    instructions: [
      'Dry shake to build foam.',
      'Add ice and shake again.',
      'Strain into a coupe.',
      'Garnish with a lemon wheel and persimmon.',
    ],
    sensoryNarrative: 'Warm whiskey and ripe persimmon over bright lemon, with a saffron-spice glow and a silky foam.',
    colorProfile: 'Warm persimmon gold',
    tint: 'oklch(78% 0.1 70)',
    glass: 'coupe',
  },
  {
    id: 'thyme-citrus-collins',
    name: 'Thyme & Citrus Collins',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Mystic'], taste: ['Frost'], accord: ['Bitter & Long'], facets: ['gin', 'herbal', 'citrus'] },
    tagline: 'A long gin Collins layered with thyme and Etna botanicals.',
    ingredients: [
      '2 oz Gin',
      '0.5 oz Bigallet Thym Liqueur',
      "0.5 oz Liquori dell'Etna",
      '0.75 oz Lemon Juice',
      'Club soda to top',
    ],
    instructions: [
      'Shake all (except soda) with ice.',
      'Strain over ice.',
      'Top with soda.',
      'Garnish with a thyme sprig.',
    ],
    sensoryNarrative: 'Bright lemon and juniper over savory thyme and botanical-citrus liqueur, long and crisp.',
    colorProfile: 'Pale herbal gold',
    tint: 'oklch(88% 0.05 110)',
    glass: 'highball',
  },
  {
    id: 'spicy-sicilian-margarita',
    name: 'Spicy Sicilian Margarita',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Hunter'], taste: ['Ember'], accord: ['Spicy & Loud'], facets: ['tequila', 'citrus', 'herbal'] },
    tagline: 'A margarita with chili amaro and an olive-leaf twist.',
    ingredients: [
      '1.5 oz Tequila',
      '0.5 oz Amaro del Capo Hot Chilli',
      '0.5 oz Olive Leaf Liqueur',
      '0.75 oz Lime Juice',
      '0.5 oz Agave syrup',
      'Tajin rim (optional)',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain into a rimmed glass.',
      'Garnish with a lime wheel.',
    ],
    sensoryNarrative: 'Crisp tequila and tart lime over chili-amaro heat, with a savory olive-leaf note and a Tajin edge.',
    colorProfile: 'Pale herbal gold',
    tint: 'oklch(82% 0.07 105)',
    glass: 'rocks',
  },
  {
    id: 'dragoncello-fizz',
    name: 'Dragoncello Fizz',
    archetype: 'The Rebel',
    tags: { identity: ['Rebel', 'Mystic'], taste: ['Frost'], accord: ['Bitter & Long'], facets: ['gin', 'herbal', 'citrus'] },
    tagline: 'A tarragon-forward gin fizz, long and savory.',
    ingredients: [
      '1.5 oz Gin',
      '0.5 oz Vicario Dragoncello (tarragon)',
      '0.75 oz Lime Juice',
      '0.5 oz Simple Syrup',
      'Club soda to top',
    ],
    instructions: [
      'Shake all (except soda) with ice.',
      'Strain over ice.',
      'Top with soda.',
      'Garnish with a tarragon sprig.',
    ],
    sensoryNarrative: 'Juniper and bright lime over anise-edged tarragon, long and crisp with a savory herbal lift.',
    colorProfile: 'Pale green-gold fizz',
    tint: 'oklch(89% 0.05 125)',
    glass: 'highball',
  },
  {
    id: 'artichoke-negroni-elevated',
    name: 'Artichoke Negroni (Elevated)',
    archetype: 'The Mystic',
    tags: { identity: ['Mystic', 'Hunter'], taste: ['Ember'], accord: ['Bitter & Long'], facets: ['amaro', 'gin', 'herbal'] },
    tagline: 'A Negroni built on artichoke and gentian bitters.',
    ingredients: [
      '1 oz Gin',
      '1 oz Artichoke Liqueur',
      '0.5 oz Sweet vermouth',
      '0.5 oz Genziano',
    ],
    instructions: [
      'Stir with ice.',
      'Strain over ice.',
      'Garnish with an orange twist.',
    ],
    sensoryNarrative: 'Earthy artichoke and gentian bitterness over juniper and vermouth, herbal and long.',
    colorProfile: 'Dark herbal amber',
    tint: 'oklch(50% 0.07 60)',
    glass: 'rocks',
  },
  {
    id: 'cretes-harvest',
    name: "Crete's Harvest",
    archetype: 'The Lover',
    tags: { identity: ['Lover', 'Rebel'], taste: ['Bloom'], accord: ['Sweet & Short'], facets: ['floral', 'citrus'] },
    tagline: 'Apple brandy and grenadine, tart and rosy.',
    ingredients: [
      '1 oz Apple Brandy',
      '0.5 oz Grenadine',
      '0.75 oz Lime Juice',
    ],
    instructions: [
      'Shake all with ice.',
      'Strain over ice.',
      'Garnish with dehydrated apple and cinnamon.',
    ],
    sensoryNarrative: 'Orchard apple over tart lime and rosy grenadine, bright and lightly sweet.',
    colorProfile: 'Rosy apple blush',
    tint: 'oklch(70% 0.1 22)',
    glass: 'rocks',
  },
];
